// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lzcpjxkttpfcgcwonrfc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx6Y3BqeGt0dHBmY2djd29ucmZjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMwMDQ3MjgsImV4cCI6MjA1ODU4MDcyOH0.ShKvEPSEEaT6jbvJ4yl56vemZhSYhY0jL5rgRI4duHc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);